// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWDojbHfilSM1RvECe8IwxgTViVsrxofI',
    appId: '1:803026354841:web:2ffcf49303fe105d48ae08',
    messagingSenderId: '803026354841',
    projectId: 'naviux-app',
    authDomain: 'naviux-app.firebaseapp.com',
    storageBucket: 'naviux-app.firebasestorage.app',
    measurementId: 'G-7WWXMR3XR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEas0fEt6R_1TKVExjjs66Nr7Nn7b_bSA',
    appId: '1:803026354841:android:ea37e24b9e4504e748ae08',
    messagingSenderId: '803026354841',
    projectId: 'naviux-app',
    storageBucket: 'naviux-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3Jdprvr4PfueID5dV7j5zSzzswyBgMlg',
    appId: '1:803026354841:ios:bcec8f8ad0e0191048ae08',
    messagingSenderId: '803026354841',
    projectId: 'naviux-app',
    storageBucket: 'naviux-app.firebasestorage.app',
    iosBundleId: 'com.naviux.naviuxApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3Jdprvr4PfueID5dV7j5zSzzswyBgMlg',
    appId: '1:803026354841:ios:bcec8f8ad0e0191048ae08',
    messagingSenderId: '803026354841',
    projectId: 'naviux-app',
    storageBucket: 'naviux-app.firebasestorage.app',
    iosBundleId: 'com.naviux.naviuxApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWDojbHfilSM1RvECe8IwxgTViVsrxofI',
    appId: '1:803026354841:web:40371a32080742fb48ae08',
    messagingSenderId: '803026354841',
    projectId: 'naviux-app',
    authDomain: 'naviux-app.firebaseapp.com',
    storageBucket: 'naviux-app.firebasestorage.app',
    measurementId: 'G-FWB0RW2DFR',
  );
}
